#!/usr/bin/env bash

# Display help usage
function usage() {
	cat <<EOM
Usage: ${0} [OPTION]

Options:
  -c, --config      Display current fan configuration
  -i, --install     Install the Argon ONE Case Fan / Argon FanHAT driver
  -u, --uninstall   Uninstall the Argon ONE Case Fan / Argon FanHAT driver
  -h, --help        Display this usage information
EOM
}

function config_argonone() {
	if [[ -f "${daemonConfigFile}" ]]; then
		echo "Current Argon fan configuration:"
		echo
		cat "${daemonConfigFile}"
	else
		echo "${daemonConfigFile} not present. Default settings will be used."
		echo "55=10"
		echo "60=55"
		echo "65=100"
	fi
	echo
	echo "Edit ${daemonConfigFile} to change your fan curve and then run"
	echo "sudo 'systemctl restart argononed.service' to activate the changes."
}

function install_argonone() {
	apt install -y python3-rpi.gpio python3-smbus i2c-tools

	if [[ ! -f "${daemonConfigFile}" ]]; then
		# Create config file for fan speed
		install -Dm644 "${sourceFilesDir}/${daemonConfigFileFilename}" "${daemonConfigFile}"
	fi

	# Install script that runs every shutdown event
	install -Dm755 "${sourceFilesDir}/${shutdownScriptFilename}" "${shutdownScript}"

	# Install script to monitor shutdown button
	install -Dm755 "${sourceFilesDir}/${powerButtonScriptFilename}" "${powerButtonScript}"

	# Stop the service if it is already present.
	if [[ -f "${daemonFanService}" ]]; then
		systemctl stop ${daemonName}.service
	fi

	# Create daemon service, running argononed
	install -Dm644 "${sourceFilesDir}/${daemonFanServiceFilename}" "${daemonFanService}"

	systemctl daemon-reload
	systemctl enable ${daemonName}.service
	systemctl start ${daemonName}.service
}

function uninstall_argonone() {
	rm -f ${powerButtonScript}
	rm -f ${shutdownScript}
	systemctl stop ${daemonName}.service
	systemctl disable ${daemonName}.service
	rm -f ${daemonFanService}
	systemctl daemon-reload
	rm -f ${daemonConfigFile}
	echo "Removed Argon One Services."
	echo "Cleanup will complete after restarting the device."
}

# Check number of command line arguments
if [[ $# -lt 1 ]]; then
	usage >&2
	exit 1
elif [[ $# -gt 1 ]]; then
	echo "[!] ERROR: Too many arguments."
	usage >&2
	exit 1
fi

# Check if the user running the script is root
if [[ "$(id -u)" -ne 0 ]]; then
	echo "[!] ERROR: You need to be root."
	exit 1
fi

if [[ "${HOSTTYPE}" != "arm" ]] && [[ "${HOSTTYPE}" != "aarch64" ]]; then
	echo "[!] ERROR: This script is only intended to run on ARM devices."
	exit 1
fi

# Check if we're running on a Raspberry Pi
if [[ -e /proc/device-tree/model ]]; then
	read -r -d $'\0' PI_MODEL </proc/device-tree/model
fi
if [[ ! "${PI_MODEL:-}" =~ ^Raspberry.Pi.*$ ]]; then
	echo "[!] ERROR: This is not a Raspberry Pi."
	exit 1
fi

# Check if we're running Ubuntu
IS_UBUNTU=$(lsb_release -is)
if [[ "${IS_UBUNTU}" != "Ubuntu" ]]; then
	echo "[!] ERROR: This script is only intended to run on Ubuntu."
	exit 1
fi

daemonName="argononed"
sourceFilesDir="files"
powerButtonScriptFilename="${daemonName}"
powerButtonScript="/usr/local/bin/${powerButtonScriptFilename}"
shutdownScriptFilename="${daemonName}-poweroff"
shutdownScript="/lib/systemd/system-shutdown/${shutdownScriptFilename}"
daemonConfigFileFilename="${daemonName}.conf"
daemonConfigFile="/etc/${daemonConfigFileFilename}"
daemonFanServiceFilename="${daemonName}.service"
daemonFanService="/lib/systemd/system/${daemonFanServiceFilename}"

# Parse command line arguments
case "${1}" in
-c | --config)
	config_argonone
	exit 0
	;;
-i | --install)
	install_argonone
	exit 0
	;;
-u | --uninstall)
	uninstall_argonone
	exit 0
	;;
-h | --help)
	usage
	exit 0
	;;
*)
	echo "[!] ERROR: \"${1}\" is not a supported parameter." >&2
	usage >@2
	exit 1
	;;
esac
