#!/bin/sh

. /etc/os-release

# Display help usage
usage() {
	cat <<EOM
Usage: ${0} [OPTION]

Options:
  -c, --config      Display current fan configuration
  -i, --install     Install the Argon ONE Case Fan / Argon FanHAT driver
  -u, --uninstall   Uninstall the Argon ONE Case Fan / Argon FanHAT driver
  -h, --help        Display this usage information
EOM
}

config_argonone() {
	if [ -f "${daemonConfigFile}" ]; then
		echo "Current Argon fan configuration:"
		echo
		cat "${daemonConfigFile}"
	else
		echo "${daemonConfigFile} not present. Default settings will be used."
		echo "55=10"
		echo "60=55"
		echo "65=100"
	fi
	echo
	echo "Edit ${daemonConfigFile} to change your fan curve and then run"
	if [ $ID = "ubuntu" ]; then
		echo "sudo systemctl restart $daemonName to activate the changes."
	elif [ $ID = "alpine" ]; then
		echo "doas rc-service $daemonName restart to activate the changes."
	fi
}

install_argonone() {
	if [ $ID = "ubuntu" ]; then
		apt install -y python3-rpi.gpio python3-smbus i2c-tools
	elif [ $ID = "alpine" ]; then
		if ! grep "^[^#]*community" /etc/apk/repositories >/dev/null 2>&1; then
			echo "Community repositories are disabled, please enable them by:"
			echo " a) Running 'setup-apkrepos -c' to setup alpine community repositories"
			echo " b) Uncommenting line ending in community in /etc/apk/repositories"
			exit 1
		fi
		apk add py3-rpigpio py3-smbus i2c-tools
	fi

	if [ ! -f "${daemonConfigFile}" ]; then
		# Create config file for fan speed
		install -Dm644 "${sourceFilesDir}/${daemonConfigFileFilename}" "${daemonConfigFile}"
	fi

	# Install script that runs every shutdown event
	install -Dm755 "${sourceFilesDir}/${shutdownScriptFilename}" "${shutdownScript}"

	# Install script to monitor shutdown button
	install -Dm755 "${sourceFilesDir}/${powerButtonScriptFilename}" "${powerButtonScript}"

	# Stop the service if it is already present.
	if [ -f "${daemonFanService}" ]; then
		if [ $ID = "ubuntu" ]; then
			systemctl stop ${daemonName}
		elif [ $ID = "alpine" ]; then
			rc-service ${daemonName} stop
			rc-update del ${daemonName} default
		fi
	fi

	# Create daemon service, running argononed
	install -Dm755 "${sourceFilesDir}/${daemonFanServiceFilename}" "${daemonFanService}"

	if [ $ID = "ubuntu" ]; then
		systemctl daemon-reload
		systemctl enable ${daemonName}
		systemctl start ${daemonName}
	elif [ $ID = "alpine" ]; then
		rc-update add ${daemonName} default
		rc-service ${daemonName} start
	fi
}

uninstall_argonone() {
	rm -f ${powerButtonScript}
	rm -f ${shutdownScript}
	if [ $ID = "ubuntu" ]; then
		systemctl stop ${daemonName}
		systemctl disable ${daemonName}
	elif [ $ID = "alpine" ]; then
		rc-service ${daemonName} stop
		rc-update del ${daemonName} default
	fi
	rm -f ${daemonFanService}
	if [ $ID = "ubuntu" ]; then
		systemctl daemon-reload
	fi
	rm -f ${daemonConfigFile}
	echo "Removed Argon One Services."
	echo "Cleanup will complete after restarting the device."
}

# Check number of command line arguments
if [ $# -lt 1 ]; then
	usage >&2
	exit 1
elif [ $# -gt 1 ]; then
	echo "[!] ERROR: Too many arguments."
	usage >&2
	exit 1
fi

# Check if the user running the script is root
if [ "$(id -u)" -ne 0 ]; then
	echo "[!] ERROR: You need to be root."
	exit 1
fi

if [ ! $HOSTTYPE = "arm" ] && [ ! $HOSTTYPE = "aarch64" ]; then
	echo "[!] ERROR: This script is only intended to run on ARM devices."
	exit 1
fi

# Check if we're running on a Raspberry Pi
if [ -e /proc/device-tree/model ]; then
	PI_MODEL="$(cat /proc/device-tree/model)"
fi
case "${PI_MODEL}" in
Raspberry*) ;;
*)
	echo "[!] ERROR: This is not a Raspberry Pi."
	exit 1
	;;
esac

if [ ! $ID = "ubuntu" ] && [ ! $ID = "alpine" ]; then
	echo "[!] ERROR: This is not a Ubuntu/Alpine."
	# TODO: add -f override option
fi

daemonName="argononed"
sourceFilesDir="files"
powerButtonScriptFilename="${daemonName}"
powerButtonScript="/usr/local/bin/${powerButtonScriptFilename}"
shutdownScriptFilename="${daemonName}-poweroff"
shutdownScript="/lib/systemd/system-shutdown/${shutdownScriptFilename}"
if [ $ID = "alpine" ]; then
	shutdownScript="/usr/local/bin/${shutdownScriptFilename}"
fi
daemonConfigFileFilename="${daemonName}.conf"
daemonConfigFile="/etc/${daemonConfigFileFilename}"
daemonFanServiceFilename="${daemonName}.service"
daemonFanService="/lib/systemd/system/${daemonFanServiceFilename}"
if [ $ID = "alpine" ]; then
	daemonFanServiceFilename="${daemonName}-rc-run"
	daemonFanService="/etc/init.d/${daemonName}"
fi

# Parse command line arguments
case "${1}" in
-c | --config)
	config_argonone
	exit 0
	;;
-i | --install)
	install_argonone
	exit 0
	;;
-u | --uninstall)
	uninstall_argonone
	exit 0
	;;
-h | --help)
	usage
	exit 0
	;;
*)
	echo "[!] ERROR: \"${1}\" is not a supported parameter." >&2
	usage >&2
	exit 1
	;;
esac
